### ISSUE TITLE
Unable to fetch snapshots

### ISSUE THREAD

**Issue by Naresh1318** [lav-kush/MotionRec#2]
Hey,

I ran `git lfs fetch` to fetch pretrained models. I get this error:

```
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/lav-kush/MotionRec.git/info/lfs'
```

**Comment by lav-kush** [comment]
Hi @Naresh1318,
Issue you faced is because of large data file limitation.
You can download the snapshots here: https://drive.google.com/drive/folders/1mWPctE8MoFuikftPHuvSlqXPSJNW7Zar?usp=sharing.
Please make sure that you are following the requirements stated by the license [1].

**Comment by lav-kush** [comment]
Hi @Naresh1318,
lfs limitation issue is fixed
You can now download history frame depth wise weights also : https://github.com/lav-kush/MotionRec/tree/master/snapshots
