### ISSUE TITLE
model.h5

### ISSUE THREAD

**Issue by TJJTJJTJJ** [lav-kush/MotionRec#4]
How to get your model model.h5 and resnet50_cvs_63.h5? 
the error is :"Downloading snapshots/model.h5 (264 MB)
Error downloading object: snapshots/model.h5 (99c52c7): Smudge error: Error downloading snapshots/model.h5 (99c52c7668338056e870714d18d2b1962148a4fa23a9ee60aea11ae5dc6c5586): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

Is there some ways to deal with?

**Comment by lav-kush** [comment]
Issue you faced is because of large data file limitation.
You can download the snapshots here: https://drive.google.com/drive/folders/1mWPctE8MoFuikftPHuvSlqXPSJNW7Zar?usp=sharing.
Please make sure that you are following the requirements stated by the license [1].

**Comment by lav-kush** [comment]
lfs limitation issue is fixed
You can now download history frame depth wise weights also : https://github.com/lav-kush/MotionRec/tree/master/snapshots
